name: Build, Push, and Scan Docker Image

on:
  push:
    branches:
      - main  # Trigger the pipeline when pushing to the main branch.
  pull_request:
    branches:
      - main  # Trigger for pull requests to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job.

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Debug: Check secrets to make sure Docker Hub credentials are being pulled
      - name: Check Docker Hub Credentials
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"

      # Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/sample-python-app:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/sample-python-app:latest

      # Install Trivy (vulnerability scanner)
      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.26.1/trivy_0.26.1_Linux-x86_64.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          rm trivy.deb

      # Scan the Docker image for vulnerabilities using Trivy
      - name: Scan Docker image with Trivy
        run: |
          trivy image --no-progress docker.io/${{ secrets.DOCKER_USERNAME }}/sample-python-app:latest
